In [8]:
import keras
import tensorflow as tf  # Import TensorFlow
frases = [
    'Hola mundo',
    'Hola a todos',
    'Hola a todo el mundo'
]
# Genera el diccionario de tokens
tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words=10)
tokenizer.fit_on_texts(frases)
print(tokenizer.word_index)

# Generación de secuencias tokenizadas
secuencias = tokenizer.texts_to_sequences(frases)
print('secuencias =', secuencias)

# Rellena las secuencias a una longuitud uniforme
relleno = tf.keras.preprocessing.sequence.pad_sequences(secuencias)
print('relleno =\n', relleno)

{'hola': 1, 'mundo': 2, 'a': 3, 'todos': 4, 'todo': 5, 'el': 6}
secuencias = [[1, 2], [1, 3, 4], [1, 3, 5, 6, 2]]


relleno =
 [[0 0 0 1 2]
 [0 0 1 3 4]
 [1 3 5 6 2]]


In [11]:
frases = [
    'Hola mundo',
    'Hola a todos',
    'Hola a todo el mundo',
    'Buen día, como estás hoy'
]
# Genera el diccionario de tokens
tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words=10)
tokenizer.fit_on_texts(frases)
print(tokenizer.word_index)

# Generación de secuencias tokenizadas
secuencias = tokenizer.texts_to_sequences(frases)
print('secuencias =', secuencias)

# Rellena las secuencias a una longuitud uniforme
relleno = tf.keras.preprocessing.sequence.pad_sequences(secuencias)
print('relleno =\n', relleno)

{'hola': 1, 'mundo': 2, 'a': 3, 'todos': 4, 'todo': 5, 'el': 6, 'buen': 7, 'día': 8, 'como': 9, 'estás': 10, 'hoy': 11}
secuencias = [[1, 2], [1, 3, 4], [1, 3, 5, 6, 2], [7, 8, 9]]
relleno =
 [[0 0 0 1 2]
 [0 0 1 3 4]
 [1 3 5 6 2]
 [0 0 7 8 9]]


In [12]:
frases = [
    'Hola mundo',
    'Hola a todos',
    'Hola a todo el mundo',
    'Buen día, como estás hoy'
]
# Genera el diccionario de tokens
tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words=10, oov_token="<OOV>")
tokenizer.fit_on_texts(frases)
word_index = tokenizer.word_index
print('\n word_index = ', word_index )

# Generación de secuencias tokenizadas
secuencias = tokenizer.texts_to_sequences(frases)
print('secuencias =', secuencias)

# Rellena las secuencias a una longuitud uniforme
relleno = tf.keras.preprocessing.sequence.pad_sequences(secuencias)
print('relleno =\n', relleno)


 word_index =  {'<OOV>': 1, 'hola': 2, 'mundo': 3, 'a': 4, 'todos': 5, 'todo': 6, 'el': 7, 'buen': 8, 'día': 9, 'como': 10, 'estás': 11, 'hoy': 12}
secuencias = [[2, 3], [2, 4, 5], [2, 4, 6, 7, 3], [8, 9, 1, 1, 1]]
relleno =
 [[0 0 0 2 3]
 [0 0 2 4 5]
 [2 4 6 7 3]
 [8 9 1 1 1]]


In [13]:
frases = [
    'Hola mundo',
    'Hola a todos',
    'Hola a todo el mundo',
    'Buen día, como estás hoy'
]
# Genera el diccionario de tokens
tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words=10, oov_token="<OOV>")
tokenizer.fit_on_texts(frases)
word_index = tokenizer.word_index
print('\n word_index = ', word_index )

# Generación de secuencias tokenizadas
secuencias = tokenizer.texts_to_sequences(frases)
print('secuencias =', secuencias)

# Rellena las secuencias a una longuitud uniforme
relleno = tf.keras.preprocessing.sequence.pad_sequences(secuencias,
                                                        padding = 'post',
                                                        truncating = 'post')
print('relleno =\n', relleno)


 word_index =  {'<OOV>': 1, 'hola': 2, 'mundo': 3, 'a': 4, 'todos': 5, 'todo': 6, 'el': 7, 'buen': 8, 'día': 9, 'como': 10, 'estás': 11, 'hoy': 12}
secuencias = [[2, 3], [2, 4, 5], [2, 4, 6, 7, 3], [8, 9, 1, 1, 1]]
relleno =
 [[2 3 0 0 0]
 [2 4 5 0 0]
 [2 4 6 7 3]
 [8 9 1 1 1]]
