In [4]:
import numpy as np
from scipy.signal import convolve2d

# Definir la matriz de entrada (señal) y el Kernel
input_matrix = np.array([[1, 2, 3, 3],
                        [4, 5, 6, 6],
                        [7, 8, 9, 9],
                        [7, 8, 9, 9]])
kernel = np.array([[0, 1, 0],
                  [-1, 1, -1],
                  [0, 1, 0]])

# Realizar la convolución 2D
output_matrix = convolve2d(input_matrix, kernel, mode='valid')

# Imprimir el resultado
print("Señal de entrada:")
print(input_matrix)
print("kernel:")
print(kernel)
print("Señal convolucionada:")
print(output_matrix)


Señal de entrada:
[[1 2 3 3]
 [4 5 6 6]
 [7 8 9 9]
 [7 8 9 9]]
kernel:
[[ 0  1  0]
 [-1  1 -1]
 [ 0  1  0]]
Señal convolucionada:
[[5 7]
 [5 7]]
