In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense, LSTM

# Paso 1: Preprocesamiento de datos (ejemplo básico)
# Serie de datos de prueba
time_series = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
print("time_series: ", time_series)
train_size = int(len(time_series) * 0.6) # tamaño conjunto entrenamiento
train_data, test_data = time_series[:train_size], time_series[train_size:]
print("train_data: ", train_data)
print("test_data: ", test_data)

time_series:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
train_data:  [0 1 2 3 4 5 6 7 8]
test_data:  [ 9 10 11 12 13 14 15]


In [2]:
# Paso 2: Preparación de datos
# Se transforman los datos en secuencias
def create_dataset(data, seq_length):
  X, y = [], []
  for i in range(len(data) - seq_length):
    X.append(data[i:i + seq_length])
    y.append(data[i + seq_length])
  return np.array(X), np.array(y)


In [3]:
# Definir el número de pasos
seq_length = 4
# Crear conjuntos de entrenamiento y prueba en formato 3D
X_train, y_train = create_dataset(train_data, seq_length)
X_test, y_test = create_dataset(test_data, seq_length)

# Imprimir los conjuntos de datos en formato 3D
print("Conjunto de datos de entrenamiento:\n", X_train)
print("Etiquetas de entrenamiento:\n", y_train)
print("Conjunto de secuencias de prueba\n:", X_test)
print("Etiquetas de prueba\n:", y_test)

Conjunto de datos de entrenamiento:
 [[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
Etiquetas de entrenamiento:
 [4 5 6 7 8]
Conjunto de secuencias de prueba
: [[ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
Etiquetas de prueba
: [13 14 15]


In [4]:
# Paso 3 Contruir el modelo
model = Sequential()
model.add(LSTM(16, activation='relu', input_shape=(seq_length, 1)))
model.add(Dense(1))
# Paso 4: Compilar y entrenar el modelo
model.compile(optimizer='adam', loss='mse')

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
# Paso 5: Entrenamiento del modelo
model.fit(X_train, y_train, epochs=500)


In [6]:
# Paso 6: Evaluación del modelo
Evaluacion = model.evaluate(X_test, y_test)
print("Evaluación del modelo:", Evaluacion)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 220ms/step - loss: 56.9677
Evaluación del modelo: 56.96773147583008


In [7]:
# Paso 7: Predicción
print("X_test: \n", X_test)
print("y_test: \n", y_test)
y_pred = model.predict(X_test)
print("y_pred: \n", y_pred)

X_test: 
 [[ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
y_test: 
 [13 14 15]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step
y_pred: 
 [[6.922275]
 [6.54289 ]
 [6.148109]]
